gigaspaces:
  version: 16.4.0
  home: /home/dixson/gigaspaces-smart-cache-enterprise-16.4.0

docker:
  username: dixsonhuie1

spring:
  framework:
    version: 5.3.29
  boot:
    version: 2.7.9

app:
  version: 1.0-SNAPSHOT
  docker:
    version: latest

