apiVersion: v1
kind: ConfigMap
metadata:
  name: application-k8s-config
  namespace: default
data:
  spring-profile: k8s

---
apiVersion: batch/v1
kind: Job
metadata:
  name: payment-feeder
  namespace: default
  labels:
    app: payment-feeder
spec:
  template:
    metadata:
      labels:
        app: payment-feeder
    spec:
      containers:
      - name: payment-feeder
        image: {{docker.username}}/payment-feeder:{{app.docker.version}}
        env:
          # Define the environment variable
          - name: spring_profiles_active
            valueFrom:
              configMapKeyRef:
                # The ConfigMap containing the value you want to assign to spring_profiles_active
                name: application-k8s-config
                # Specify the key associated with the value
                key: spring-profile
      restartPolicy: Never
  backoffLimit: 2
