gigaspaces:
  version: 17.3.0
  home: /home/dixson/gigaspaces-smart-cache-enterprise-17.3.0

docker:
  username: dixsonhuie1

spring:
  framework:
    version: 7.0.8
  boot:
    version: 3.4.9

springdoc:
  version: 2.8.15

app:
  version: 1.0-SNAPSHOT
  docker:
    version: latest

