gigaspaces:
  version: 17.1.5
  home: /home/dixson/gigaspaces-smart-cache-enterprise-17.1.5

docker:
  username: dixsonhuie1

spring:
  framework:
    version: 6.2.10
  boot:
    version: 3.4.9

springdoc:
  version: 2.8.15

app:
  version: 1.0-SNAPSHOT
  docker:
    version: latest

