apiVersion: v1
kind: ConfigMap
metadata:
  name: application-k8s-config
  namespace: default
data:
  spring-profile: k8s

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-app
  namespace: default
  labels:
    app: rest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-app
  template:
    metadata:
      labels:
        app: rest-app
    spec:
      containers:
        - name: rest-app
          image: {{docker.username}}/rest-app:{{app.docker.version}}
          imagePullPolicy: Always
          ports:
            # the port number should match the server.port in application.properties
            - name: rest-app-web
              containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: "/"
              port: rest-app-web
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "/"
              port: rest-app-web
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            # Define the environment variable
            - name: spring_profiles_active
              valueFrom:
                configMapKeyRef:
                  # The ConfigMap containing the value you want to assign to spring_profiles_active
                  name: application-k8s-config
                  # Specify the key associated with the value
                  key: spring-profile

---
apiVersion: v1
kind: Service
metadata:
  name: rest-app
  namespace: default
  labels:
    app: rest-app
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: rest-app
